### ISSUE TITLE
npm start returns error

### ISSUE THREAD

**Issue by uneart** [rogic89/ToDo-react-redux-immutable#2]
Hi there,

I am trying to get the example code working locally. I cloned it and ran `npm install` but `npm start` returned the following error (I replaced the original path here for privacy):

```
ERROR in ./src/init.js
Module build failed: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:374:36
    at /PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:396:22
    at Array.map (native)
    at OptionManager.resolvePresets (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
    at OptionManager.mergePresets (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
    at OptionManager.mergeOptions (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328:14)
    at /PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:370:14
    at /PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:390:24
    at Array.map (native)
    at OptionManager.resolvePresets (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:385:20)
    at OptionManager.mergePresets (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:10)
    at OptionManager.mergeOptions (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:328:14)
    at OptionManager.addConfig (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:10)
    at OptionManager.findConfigs (/PATH/TO/REPOSITORY/node_modules/babel-core/lib/transformation/file/options/option-manager.js:434:16)
 @ multi app
```

Any idea why this happens? I user npm version 3.9.3 and node version 6.2.0.

**Comment by rogic89** [comment]
Hmm I am not really sure what happens, but it works fine for me and for everyone else who tried. Check this link https://github.com/webpack/webpack/issues/2463 , its probably a node version problem. 

For me:
$ node -v
**v4.4.6**
$ npm -v
**2.15.5**

**Comment by uneart** [comment]
That seemed to be the issue. Downgraded to node v4.4.7 and now it works perfectly. Thank you for the hint! Having nodeJS updated to one of the latest versions seems to cause more problems than it solves 👎

**Comment by rogic89** [comment]
cool cool, glad I could help
